modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="wzoregen" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wizard1st's World Ore Generate for content(s)." #mandatory
displayURL="https://www.youtube.com/wizard1stmedia/" #optional
logoFile="wzoregen.png" #optional
credits="Wizard1st" #optional
authors="Wizard1st" #optional
description='''
Subscribe me for more contents.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.wzoregen]] #optional
    # the modid of the dependency
    modId="wzoregen" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.wzoregen]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
